### ISSUE TITLE
Is there a way to turn On/Off each camera ?

### ISSUE THREAD

**Issue by tcellerier** [tchellomello/python-arlo#39]
Hello,

In the settings of my Arlo camera, I can turn the camera On or Off. (button Camera On/Off)
Is there a way to do it in this python library ?

Thanks
Thomas

**Comment by jwillaz** [comment]
I'm not sure about On/Off, but you can definitely disable/enable motion detection on each camera.  This seems like a better solution to me because it still gives you the ability to view the Live feed on a camera without having to go turn it back on.  The only shortcoming is that there is no indicator in the Arlo app UI that motion detection is disabled - you would have to rely on whatever interface you are using to disable it (e.g. Home Assistant).  Individual On/Off should be possible to implement, though.  It's an option in SmartThings, and I was using it via MQTT prior to the enable/disable motion functions being made available for the Home Assistant component.

**Comment by viswa-swami** [comment]
I believe there is an on/off or enable/disable in the camera properties or base station properties.

There are functions in this library to print the camera properties and base station properties.  If you print it, you can check if such a property exists.  Toggling that property will turn on/off the camera.

**Comment by tcellerier** [comment]
It looks like the On/Off option is hold by the property privacyActive (True means Camera Off) listed from the command base.get_camera_properties
However I couldn't manage to toggle it with any of the following commands :
arlo.cameras[0].privacyActive = True
or arlo.base_stations[0].privacyActive = True
even with also cam.update() afterwards

Any idea ?

**Comment by jwillaz** [comment]
Just submitted a PR implementing this.
